ARG PHP_VERSION=php82-fpm
FROM michielgerritsen/magento2-base-image:${PHP_VERSION}

ARG MAGENTO_VERSION=2.4.6
ARG MAGENTO_TYPE=project-community-edition

ENV CI=true
ENV URL=http://localhost/
ENV FLAT_TABLES=false

COPY scripts/retry retry
COPY patches/ patches/
COPY scripts/apply-2.4-patches.php scripts/apply-2.4-patches.php
COPY scripts/allow-composer-plugins.php scripts/allow-composer-plugins.php
COPY templates/memory-limit-php.ini /usr/local/etc/php/conf.d/memory-limit-php.ini

RUN set -e; \
    ./start-services && \
    echo "[cad] Composer version:" && \
    composer --version && \
    echo "[cad] Downloading & unzipping Magento" && \
    curl --fail-with-body -o magento.zip https://mirror.mage-os.org/packages/magento/$MAGENTO_TYPE-$MAGENTO_VERSION.zip && \
    unzip -q magento.zip -d . && \
    rm magento.zip && \
    echo "[cad] Allowing composer plugins" && \
    php scripts/allow-composer-plugins.php && \
    rm scripts/allow-composer-plugins.php && \
    composer config --unset repositories.0 && \
    composer config repositories.mageos composer https://mirror.mage-os.org/ && \
    ./retry "composer update --no-security-blocking" && \
    composer config --no-plugins allow-plugins.yireo/magento2-replace-tools true && \
    ./retry "composer require --dev yireo/magento2-replace-tools --with-dependencies" && \
    ./retry "composer replace:bulk:add yireo/magento2-replace-all" && \
    ./retry "composer replace:build" && \
    ./retry "composer update --lock" && \
    if [ -f "/data/vendor/magento/module-inventory-catalog/etc/communication.xml" ]; then sed -i 's/is_synchronous="false"//g' /data/vendor/magento/module-inventory-catalog/etc/communication.xml; fi && \
    if [ -f "/data/vendor/magento/module-inventory-sales/etc/communication.xml" ]; then sed -i 's/is_synchronous="false"//g' /data/vendor/magento/module-inventory-sales/etc/communication.xml; fi && \
    if [ -f "/data/vendor/magento/module-inventory-indexer/etc/communication.xml" ]; then sed -i 's/is_synchronous="false"//g' /data/vendor/magento/module-inventory-indexer/etc/communication.xml; fi && \
    echo "[cad] Running Magento setup:install" && \
    php bin/magento setup:install --backend-frontname=admin --session-save=db --db-host=127.0.0.1 --db-name=magento --db-user=magento --db-password=password --base-url=http://localhost --timezone=Europe/Amsterdam --currency=EUR --admin-user=exampleuser --admin-password=examplepassword123 --admin-email=user@example.com --admin-firstname=Example --admin-lastname=Example --use-rewrites=1 && \
    php bin/magento deploy:mode:set developer && \
    php bin/magento setup:static-content:deploy en_US -f -j 12 && \
    php bin/magento setup:di:compile && \
    php bin/magento indexer:reindex && \
    mkdir -p extensions && \
    composer config repositories.dev-extensions path extensions/* && \
    composer require --dev phpstan/phpstan:~1.7 bitexpert/phpstan-magento && \
    php scripts/apply-2.4-patches.php && \
    rm scripts/apply-2.4-patches.php && \
    ./stop-services

COPY templates/install-config-mysql.php dev/tests/integration/etc/
COPY templates/post-install-setup-command-config.php dev/tests/integration/etc/
COPY templates/phpunit-unit.xml dev/tests/unit/phpunit.xml
COPY templates/phpunit-integration.xml dev/tests/integration/phpunit.xml
COPY entrypoint.sh entrypoint.sh

COPY scripts/enable-flat-catalog enable-flat-catalog
COPY scripts/change-base-url change-base-url
COPY scripts/install-composer-package install-composer-package
COPY scripts/disable-2fa disable-2fa

RUN chmod +x enable-flat-catalog && chmod +x change-base-url

ENTRYPOINT ["/bin/bash", "entrypoint.sh"]

EXPOSE 80 3306
