ARG PHP_VERSION=php74-fpm
FROM michielgerritsen/magento2-base-image:${PHP_VERSION}

ARG MAGENTO_VERSION=2.4.4
ARG MAGENTO_TYPE=project-community-edition
ARG SAMPLE_DATA=false

ENV CI=true
ENV URL=http://localhost/
ENV FLAT_TABLES=false

COPY scripts/retry retry
COPY patches/ patches/
COPY scripts/apply-2.4-patches.php scripts/apply-2.4-patches.php
COPY scripts/downgrade-monolog.php scripts/downgrade-monolog.php
COPY scripts/allow-composer-plugins.php scripts/allow-composer-plugins.php

# Comes from Github Actions
COPY vendor /data/vendor

RUN ./start-services && \
    if (( $(php -r 'echo version_compare(getenv("MAGENTO_VERSION"), "2.4.2", "<=") ? "true" : "false";') = "true" )); then composer self-update --1; else composer self-update --2; fi && \
    echo "Composer version:" && \
    composer --version && \
    curl -o magento.zip https://repo-magento-mirror.fooman.co.nz/dist/magento/$MAGENTO_TYPE/magento-$MAGENTO_TYPE-$MAGENTO_VERSION.zip && \
    unzip -q magento.zip -d . && \
    rm magento.zip && \
    if (( $(php -r 'echo version_compare(getenv("MAGENTO_VERSION"), "2.4.2", "<=") ? "true" : "false";') = "true" )); then echo "Using Composer version 1 so skipping allow-plugins"; else php scripts/allow-composer-plugins.php rm scripts/allow-composer-plugins.php; fi && \
    composer config --unset repositories.0 && \
    composer config repositories.fooman composer https://repo-magento-mirror.fooman.co.nz/ && \
    ./retry "composer install" && \
    php scripts/downgrade-monolog.php && \
    if [ -f "/data/vendor/magento/module-inventory-catalog/etc/communication.xml" ]; then sed -i 's/is_synchronous="false"//g' /data/vendor/magento/module-inventory-catalog/etc/communication.xml; fi && \
    if [ -f "/data/vendor/magento/module-inventory-sales/etc/communication.xml" ]; then sed -i 's/is_synchronous="false"//g' /data/vendor/magento/module-inventory-sales/etc/communication.xml; fi && \
    if [ -f "/data/vendor/magento/module-inventory-indexer/etc/communication.xml" ]; then sed -i 's/is_synchronous="false"//g' /data/vendor/magento/module-inventory-indexer/etc/communication.xml; fi && \
    composer dump-autoload && \
    php bin/magento setup:install --backend-frontname=admin --session-save=db --db-host=127.0.0.1 --db-name=magento --db-user=magento --db-password=password --base-url=http://localhost --timezone=Europe/Amsterdam --currency=EUR --admin-user=exampleuser --admin-password=examplepassword123 --admin-email=user@example.com --admin-firstname=Example --admin-lastname=Example --use-rewrites=1 --use-sample-data && \
    php bin/magento deploy:mode:set developer && \
    if [ "${SAMPLE_DATA}" = "true" ]; then php bin/magento sampledata:deploy; fi && \
    if [ "${SAMPLE_DATA}" = "true" ]; then php bin/magento setup:upgrade; fi && \
    php bin/magento setup:static-content:deploy en_US -f -j 12 && \
    php bin/magento setup:di:compile && \
    magerun2 indexer:reindex && \
    mkdir -p extensions && \
    composer config repositories.dev-extensions path extensions/* && \
    composer require --dev phpstan/phpstan:~1.7 bitexpert/phpstan-magento && \
    php scripts/apply-2.4-patches.php && \
    rm scripts/apply-2.4-patches.php && \
    rm scripts/downgrade-monolog.php

COPY templates/install-config-mysql.php dev/tests/integration/etc/
COPY templates/post-install-setup-command-config.php dev/tests/integration/etc/
COPY templates/phpunit-unit.xml dev/tests/unit/phpunit.xml
COPY templates/phpunit-integration.xml dev/tests/integration/phpunit.xml
COPY entrypoint.sh entrypoint.sh

COPY scripts/enable-flat-catalog enable-flat-catalog
COPY scripts/change-base-url change-base-url
COPY scripts/install-composer-package install-composer-package
COPY scripts/disable-2fa disable-2fa

RUN chmod +x enable-flat-catalog && chmod +x change-base-url

ENTRYPOINT ["/bin/bash", "entrypoint.sh"]

EXPOSE 80 3306
