ARG PHP_VERSION=php74-fpm
FROM michielgerritsen/magento2-base-image:${PHP_VERSION}

ARG MAGENTO_VERSION=2.4.1
ARG MAGENTO_TYPE=project-community-edition
ARG SAMPLE_DATA=false

ENV CI=true
ENV URL=http://localhost/
ENV FLAT_TABLES=false
ENV COMPOSER_VERSION=1

COPY scripts/retry retry
COPY scripts/install-phpstan.php scripts/install-phpstan.php
COPY patches/vertex-compilation-issue.patch vertex-compilation-issue.patch
COPY patches/APSB22-12/MDVA-43395_EE_2.4.3-p1_COMPOSER_v1.patch MDVA-43395_EE_2.4.3-p1_COMPOSER_v1.patch
COPY patches/APSB22-12/MDVA-43443_EE_2.3.4_COMPOSER_v1.patch MDVA-43443_EE_2.3.4_COMPOSER_v1.patch
COPY patches/APSB22-12/MDVA-43443_EE_2.4.2-p2_COMPOSER_v1.patch MDVA-43443_EE_2.4.2-p2_COMPOSER_v1.patch

# Comes from Github Actions
COPY vendor /data/vendor

RUN ./start-services && \
    curl -o magento.zip https://repo-magento-mirror.fooman.co.nz/dist/magento/$MAGENTO_TYPE/magento-$MAGENTO_TYPE-$MAGENTO_VERSION.zip && \
    unzip -q magento.zip -d . && \
    rm magento.zip && \
    composer config --unset repositories.0 && \
    composer config repositories.fooman composer https://repo-magento-mirror.fooman.co.nz/ && \
    ./retry "composer install" && \
    if [ -f "/data/vendor/magento/module-inventory-catalog/etc/communication.xml" ]; then sed -i 's/is_synchronous="false"//g' /data/vendor/magento/module-inventory-catalog/etc/communication.xml; fi && \
    if [ -f "/data/vendor/magento/module-inventory-sales/etc/communication.xml" ]; then sed -i 's/is_synchronous="false"//g' /data/vendor/magento/module-inventory-sales/etc/communication.xml; fi && \
    if [ -f "/data/vendor/magento/module-inventory-indexer/etc/communication.xml" ]; then sed -i 's/is_synchronous="false"//g' /data/vendor/magento/module-inventory-indexer/etc/communication.xml; fi && \
    php bin/magento setup:install --backend-frontname=admin --session-save=db --db-host=127.0.0.1 --db-name=magento --db-user=magento --db-password=password --base-url=http://localhost --timezone=Europe/Amsterdam --currency=EUR --admin-user=exampleuser --admin-password=examplepassword123 --admin-email=user@example.com --admin-firstname=Example --admin-lastname=Example --use-rewrites=1 --use-sample-data && \
    php bin/magento deploy:mode:set developer && \
    if (( $(php -r 'echo version_compare(getenv("MAGENTO_VERSION"), "2.3.3", ">") ? "true" : "false";') = "true" )); then echo "applying MDVA-43395_EE_2.4.3-p1_COMPOSER_v1.patch"; git apply MDVA-43395_EE_2.4.3-p1_COMPOSER_v1.patch; fi && \
    if (( $(php -r 'echo version_compare(getenv("MAGENTO_VERSION"), "2.3.3-p1", ">=") && version_compare(getenv("MAGENTO_VERSION"), "2.3.4", "<=") ? "true" : "false";') = "true" )); then echo "applying MDVA-43443_EE_2.3.4_COMPOSER_v1.patch"; git apply MDVA-43443_EE_2.3.4_COMPOSER_v1.patch; fi && \
    if (( $(php -r 'echo version_compare(getenv("MAGENTO_VERSION"), "2.3.4-p2", ">=") ? "true" : "false";') = "true" )); then echo "applying MDVA-43443_EE_2.4.2-p2_COMPOSER_v1.patch"; git apply MDVA-43443_EE_2.4.2-p2_COMPOSER_v1.patch; fi && \
    if (( $(php -r 'echo substr(getenv("MAGENTO_VERSION"), 0, 5) == "2.3.3" ? "true" : "false";') = "true" )); then echo "applying vertex-compilation-issue.patch"; git apply vertex-compilation-issue.patch; fi && \
    echo "Running scconnector_google_remove_cl queries" && \
    mysql -u root magento -e 'CREATE TABLE IF NOT EXISTS `scconnector_google_remove_cl` (`version_id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT "Version ID", `entity_id` int(10) unsigned NOT NULL DEFAULT "0" COMMENT "Entity ID", PRIMARY KEY (`version_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT="scconnector_google_remove_cl";' && \
    mysql -u root magento -e 'INSERT INTO `scconnector_google_remove_cl` (`version_id`, `entity_id`) VALUES ('1', '1');' && \
    mysql -u root magento -e 'alter table `scconnector_google_remove_cl` auto_increment = 1;' && \
    if [ "${SAMPLE_DATA}" = "true" ]; then echo "Running php bin/magento sampledata:deploy"; php bin/magento sampledata:deploy; fi && \
    if [ "${SAMPLE_DATA}" = "true" ]; then echo "Running setup:upgrade" && (php bin/magento setup:upgrade || php bin/magento setup:upgrade || php bin/magento setup:upgrade); fi && \
    php bin/magento setup:static-content:deploy en_US -f -j 12 && \
    php bin/magento setup:di:compile && \
    php bin/magento indexer:reindex && \
    mkdir -p extensions && \
    composer config repositories.dev-extensions path extensions/* && \
    php scripts/install-phpstan.php && \
    rm scripts/install-phpstan.php

COPY patches/cors.patch cors.patch
COPY templates/install-config-mysql.php dev/tests/integration/etc/
COPY templates/post-install-setup-command-config.php dev/tests/integration/etc/
COPY templates/phpunit-unit.xml dev/tests/unit/phpunit.xml
COPY templates/phpunit-integration.xml dev/tests/integration/phpunit.xml
COPY entrypoint.sh entrypoint.sh

COPY scripts/enable-flat-catalog enable-flat-catalog
COPY scripts/change-base-url change-base-url
COPY scripts/install-composer-package install-composer-package

RUN chmod +x enable-flat-catalog && chmod +x change-base-url

RUN git apply cors.patch && rm cors.patch vertex-compilation-issue.patch

ENTRYPOINT ["/bin/bash", "entrypoint.sh"]

EXPOSE 80 3306
