ARG PHP_VERSION=php74-fpm
FROM michielgerritsen/magento2-base-image:${PHP_VERSION}

ARG MAGENTO_VERSION=2.4.4
ARG MAGENTO_TYPE=project-community-edition
ARG SAMPLE_DATA=false
ARG DISABLE_2FA=true
ARG COMPOSER_AUTH={}

ENV CI=true
ENV URL=http://localhost/
ENV FLAT_TABLES=false
ENV COMPOSER_ALLOW_SUPERUSER=1

COPY scripts/retry retry
COPY patches/ patches/
COPY scripts/apply-2.4-patches.php scripts/apply-2.4-patches.php
COPY scripts/downgrade-monolog.php scripts/downgrade-monolog.php
COPY scripts/upgrade-to-composer-2.php scripts/upgrade-to-composer-2.php
COPY scripts/allow-composer-plugins.php scripts/allow-composer-plugins.php
COPY scripts/remove-paypal-braintree.php scripts/remove-paypal-braintree.php
COPY scripts/patch-AC2855.php scripts/patch-AC2855.php
COPY templates/memory-limit-php.ini /usr/local/etc/php/conf.d/memory-limit-php.ini

RUN set -e; \
    ./start-services && \
    composer self-update --2 && \
    echo "[cad] Composer version:" && \
    composer --version && \
    if [ "$MAGENTO_VERSION" = "2.4.9-alpha3" ]; then \
        echo "[cad] Downloading Magento" && \
        composer create-project --repository-url=https://repo.magento.com/ magento/$MAGENTO_TYPE=$MAGENTO_VERSION build && \
        mv build/* . && \
        for f in build/.*; do [ "$f" != "build/." ] && [ "$f" != "build/.." ] && mv "$f" .; done && \
        rm -rf build; \
    else \
        echo "[cad] Downloading & unzipping Magento" && \
        curl --fail-with-body -o magento.zip https://repo-magento-mirror.fooman.co.nz/dist/magento/$MAGENTO_TYPE/magento-$MAGENTO_TYPE-$MAGENTO_VERSION.zip && \
        unzip -q magento.zip -d . && \
        rm magento.zip; \
    fi && \
    echo "[cad] Allowing composer plugins" && \
    php scripts/allow-composer-plugins.php && \
    rm scripts/allow-composer-plugins.php && \
    echo "[cad] Upgrading to composer 2" && \
    php scripts/upgrade-to-composer-2.php && \
    rm scripts/upgrade-to-composer-2.php && \
    if [ "$MAGENTO_VERSION" != "2.4.9-alpha3" ]; then \
        composer config --unset repositories.0 && \
        composer config repositories.fooman composer https://repo-magento-mirror.fooman.co.nz/; \
    fi && \
    if [ "$MAGENTO_VERSION" = "2.4.4" ]; then composer require "magento/security-package:1.1.3-p1 as 1.1.3" --no-update; fi && \
    if [ "$MAGENTO_VERSION" = "2.4.4" ]; then composer require "magento/inventory-metapackage:1.2.4-p1 as 1.2.4" --no-update; fi && \
    echo "[cad] Running Composer install" && \
    ./retry "composer install" && \
    php scripts/patch-AC2855.php && \
    php scripts/downgrade-monolog.php && \
    php scripts/remove-paypal-braintree.php && \
    echo "[cad] Updating XML" && \
    if [ -f "/data/vendor/magento/module-inventory-catalog/etc/communication.xml" ]; then sed -i 's/is_synchronous="false"//g' /data/vendor/magento/module-inventory-catalog/etc/communication.xml; fi && \
    if [ -f "/data/vendor/magento/module-inventory-sales/etc/communication.xml" ]; then sed -i 's/is_synchronous="false"//g' /data/vendor/magento/module-inventory-sales/etc/communication.xml; fi && \
    if [ -f "/data/vendor/magento/module-inventory-indexer/etc/communication.xml" ]; then sed -i 's/is_synchronous="false"//g' /data/vendor/magento/module-inventory-indexer/etc/communication.xml; fi && \
    composer dump-autoload && \
    echo "[cad] Running Magento setup:install" && \
    php bin/magento setup:install --backend-frontname=admin --session-save=db --db-host=127.0.0.1 --db-name=magento --db-user=magento --db-password=password --base-url=http://localhost --timezone=Europe/Amsterdam --currency=EUR --admin-user=exampleuser --admin-password=examplepassword123 --admin-email=user@example.com --admin-firstname=Example --admin-lastname=Example --use-rewrites=1 --use-sample-data && \
    echo "[cad] Setting developer mode" && \
    php bin/magento deploy:mode:set developer && \
    if [ "${SAMPLE_DATA}" = "true" ] && [ "$MAGENTO_VERSION" != "2.4.9-alpha3" ]; then echo "[cad] Running php bin/magento sampledata:deploy"; php bin/magento sampledata:deploy; fi && \
    if [ "${SAMPLE_DATA}" = "true" ] && [ "$MAGENTO_VERSION" = "2.4.9-alpha3" ]; then echo "[cad] Installing sampledata"; composer require magento/module-bundle-sample-data magento/module-catalog-sample-data magento/module-sales-sample-data magento/module-customer-sample-data magento/module-cms-sample-data magento/module-widget-sample-data magento/module-theme-sample-data magento/module-downloadable-sample-data magento/module-wishlist-sample-data magento/module-review-sample-data magento/module-tax-sample-data magento/module-catalog-rule-sample-data magento/module-configurable-sample-data magento/module-product-links-sample-data magento/module-sales-rule-sample-data magento/module-msrp-sample-data magento/module-grouped-product-sample-data magento/module-swatches-sample-data magento/module-offline-shipping-sample-data magento/sample-data-media --ignore-platform-reqs; fi && \
    if [ "${SAMPLE_DATA}" = "true" ]; then echo "[cad] Running setup:upgrade" && ./retry "php bin/magento setup:upgrade"; fi && \
    php bin/magento setup:static-content:deploy en_US -f -j 12 && \
    php bin/magento setup:di:compile && \
    php bin/magento indexer:reindex && \
    mkdir -p extensions && \
    composer config repositories.dev-extensions path extensions/* && \
    composer require --dev phpstan/phpstan bitexpert/phpstan-magento phpstan/extension-installer && \
    php scripts/apply-2.4-patches.php && \
    rm scripts/apply-2.4-patches.php && \
    rm scripts/downgrade-monolog.php && \
    git config --global --add safe.directory '*' && \
    ./stop-services

COPY templates/supervisord-webserver.conf /etc/supervisor/conf.d/webserver.conf
COPY templates/install-config-mysql.php dev/tests/integration/etc/
COPY templates/post-install-setup-command-config.php dev/tests/integration/etc/
COPY entrypoint.sh entrypoint.sh

COPY scripts/enable-flat-catalog enable-flat-catalog
COPY scripts/change-base-url change-base-url
COPY scripts/install-composer-package install-composer-package
COPY scripts/disable-2fa disable-2fa

COPY templates/phpunit-integration.xml dev/tests/integration/phpunit.xml
COPY templates/phpunit-integration-248.xml dev/tests/integration/phpunit-248.xml
COPY templates/phpunit-unit.xml dev/tests/unit/phpunit.xml
COPY templates/phpunit-unit-248.xml dev/tests/unit/phpunit-248.xml
COPY scripts/fix-phpunit.xml.php fix-phpunit.xml.php

RUN chmod +x enable-flat-catalog && \
    chmod +x change-base-url && \
    php fix-phpunit.xml.php && \
    rm fix-phpunit.xml.php && \
    rm dev/tests/integration/phpunit-248.xml && \
    rm dev/tests/unit/phpunit-248.xml

ENTRYPOINT ["/bin/bash", "entrypoint.sh"]

EXPOSE 80 3306
