#!/bin/bash

if [ "$#" -eq 0 ]; then
  echo "Please provide at least one argument."
  exit 1
fi

packages=""
for package in "$@"
do
  packages="$packages $package"
done

composer require $packages --no-plugins --no-interaction